#!/usr/bin/env python3
"""
Generate one quiz JSON per Big Print chapter.
"""

from __future__ import annotations

import json
from pathlib import Path


QUIZZES = [
    {
        "chapter_id": "01-america-is-broken",
        "question_en": "What does the chapter identify as a structural force that pushes wealth upward?",
        "choices_en": [
            "Inflation built into the financial system",
            "Population decline",
            "Gold scarcity",
            "Balanced federal budgets",
        ],
        "question_ko": "이 장은 무엇을 부를 위로 끌어올리는 구조적 힘으로 제시하는가?",
        "choices_ko": [
            "금융 시스템에 내장된 인플레이션",
            "인구 감소",
            "금 부족",
            "균형 재정",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter argues that inflation is built into the American financial system and redistributes wealth upward.",
        "explanation_ko": "이 장은 인플레이션이 미국 금융 시스템에 내장되어 있으며 부를 위로 재분배한다고 본다.",
    },
    {
        "chapter_id": "02-inflation-is-the-cause",
        "question_en": "How is inflation primarily defined in this chapter?",
        "choices_en": [
            "As the result of money-supply expansion",
            "As a random change in consumer mood",
            "As technological progress",
            "As the elimination of debt",
        ],
        "question_ko": "이 장에서 인플레이션은 주로 어떻게 정의되는가?",
        "choices_ko": [
            "통화 공급 확대의 결과",
            "소비자 심리의 무작위 변화",
            "기술 진보",
            "부채의 제거",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter defines inflation as a monetary phenomenon driven by expansion of the money supply.",
        "explanation_ko": "이 장은 인플레이션을 통화 공급 확대가 낳는 통화 현상으로 정의한다.",
    },
    {
        "chapter_id": "03-money-sound-and-fiat",
        "question_en": "Which contrast is central to this chapter?",
        "choices_en": [
            "Sound money versus fiat money",
            "Stocks versus bonds",
            "Imports versus exports",
            "Cities versus farms",
        ],
        "question_ko": "이 장의 중심 대비는 무엇인가?",
        "choices_ko": [
            "건전 화폐와 법정화폐",
            "주식과 채권",
            "수입과 수출",
            "도시와 농촌",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter contrasts sound money, which preserves integrity, with fiat money, which expands by political discretion.",
        "explanation_ko": "이 장은 무결성을 지키는 건전 화폐와 정치적 재량으로 팽창하는 법정화폐를 대비한다.",
    },
    {
        "chapter_id": "04-sound-money-is-a-moral-issue",
        "question_en": "Why is sound money treated as a moral issue?",
        "choices_en": [
            "Because fair exchange depends on honest measures",
            "Because it increases entertainment spending",
            "Because it removes all taxes",
            "Because it guarantees equal outcomes",
        ],
        "question_ko": "건전 화폐가 도덕적 문제로 다뤄지는 이유는 무엇인가?",
        "choices_ko": [
            "공정한 교환이 정직한 척도에 달려 있기 때문",
            "오락 소비를 늘리기 때문",
            "모든 세금을 없애기 때문",
            "결과의 완전한 평등을 보장하기 때문",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter links sound money to honest measurement and justice in exchange.",
        "explanation_ko": "이 장은 건전 화폐를 정직한 측정과 공정한 교환의 정의에 연결한다.",
    },
    {
        "chapter_id": "05-classical-economics",
        "question_en": "According to this chapter, real prosperity grows mainly through what?",
        "choices_en": [
            "Saving and capital formation",
            "Constant stimulus spending",
            "Permanent negative rates",
            "Removing prices from markets",
        ],
        "question_ko": "이 장에 따르면 실질적 번영은 주로 무엇을 통해 성장하는가?",
        "choices_ko": [
            "저축과 자본 형성",
            "끊임없는 경기 부양 지출",
            "영구적 마이너스 금리",
            "가격 신호의 제거",
        ],
        "answer_index": 0,
        "explanation_en": "Classical economics is presented as a framework in which saving and capital formation drive growth.",
        "explanation_ko": "이 장은 고전파 경제학에서 저축과 자본 형성이 성장의 기반이라고 본다.",
    },
    {
        "chapter_id": "06-the-path-to-pure-fiat-1789-1971",
        "question_en": "What long-term direction does the chapter trace in U.S. monetary history?",
        "choices_en": [
            "A gradual move toward pure fiat money",
            "A return to barter",
            "A permanent silver standard",
            "The end of banking conflict",
        ],
        "question_ko": "이 장은 미국 통화사에서 어떤 장기적 방향을 추적하는가?",
        "choices_ko": [
            "순수 법정화폐로의 점진적 이동",
            "물물교환으로의 회귀",
            "영구적 은본위제",
            "은행 갈등의 종결",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter describes a cumulative historical path that weakens restraint and leads toward pure fiat.",
        "explanation_ko": "이 장은 절제 장치가 약화되며 순수 법정화폐로 가는 누적적 경로를 설명한다.",
    },
    {
        "chapter_id": "07-1971-to-present-financialization-bailouts-free-money",
        "question_en": "What pattern defines the post-1971 era in this chapter?",
        "choices_en": [
            "Financialization, bailouts, and cheap money",
            "Stable sound-money discipline",
            "Falling state intervention",
            "The disappearance of debt",
        ],
        "question_ko": "이 장에서 1971년 이후 시대를 규정하는 패턴은 무엇인가?",
        "choices_ko": [
            "금융화, 구제금융, 값싼 돈",
            "안정적인 건전 화폐 절제",
            "국가 개입의 축소",
            "부채의 소멸",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter sees the post-1971 period as one of growing financialization, serial bailouts, and progressively cheaper money.",
        "explanation_ko": "이 장은 1971년 이후를 심화되는 금융화, 반복적 구제금융, 값싼 돈의 시대로 본다.",
    },
    {
        "chapter_id": "08-the-federal-reserve",
        "question_en": "What unique power of the Fed is emphasized here?",
        "choices_en": [
            "Creating money out of thin air",
            "Abolishing all taxes",
            "Setting world trade quotas",
            "Owning all private banks",
        ],
        "question_ko": "이 장에서 강조되는 연준의 독보적 권한은 무엇인가?",
        "choices_ko": [
            "무에서 화폐를 창조하는 것",
            "모든 세금을 폐지하는 것",
            "세계 무역 쿼터를 정하는 것",
            "모든 민간 은행을 소유하는 것",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter centers the Fed’s power to create money as the key institutional force in the current system.",
        "explanation_ko": "이 장은 화폐 창조 권한을 현재 체제의 핵심 제도 권력으로 본다.",
    },
    {
        "chapter_id": "09-keynesians-and-modern-monetary-theory-mmt",
        "question_en": "What does the chapter suggest about policy and economic theory?",
        "choices_en": [
            "Policy follows underlying theory",
            "Policy has nothing to do with theory",
            "Theory matters only in recessions",
            "Only voters determine theory",
        ],
        "question_ko": "이 장은 정책과 경제 이론의 관계를 어떻게 보나?",
        "choices_ko": [
            "정책은 밑바탕의 이론을 따른다",
            "정책은 이론과 무관하다",
            "이론은 불황기에만 중요하다",
            "유권자만이 이론을 결정한다",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter argues that different theories generate different policy regimes and outcomes.",
        "explanation_ko": "이 장은 서로 다른 이론이 서로 다른 정책 체제와 결과를 만든다고 본다.",
    },
    {
        "chapter_id": "10-steins-law",
        "question_en": "What does Stein’s Law mean in this context?",
        "choices_en": [
            "What cannot continue forever will stop",
            "Every debt problem solves itself",
            "Inflation always lowers debt pain",
            "Growth permanently outruns leverage",
        ],
        "question_ko": "이 맥락에서 스타인의 법칙은 무엇을 뜻하는가?",
        "choices_ko": [
            "영원히 지속될 수 없는 것은 결국 멈춘다",
            "모든 부채 문제는 스스로 해결된다",
            "인플레이션은 언제나 부채 부담을 줄인다",
            "성장은 항상 레버리지를 앞선다",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter uses Stein’s Law to stress the inevitability of an end to unsustainable debt growth.",
        "explanation_ko": "이 장은 지속 불가능한 부채 경로가 결국 끝날 수밖에 없다는 필연성을 강조한다.",
    },
    {
        "chapter_id": "11-nothing-stops-this-train",
        "question_en": "What image does the chapter use for America’s fiscal path?",
        "choices_en": [
            "A train that can no longer be stopped normally",
            "A ship returning safely to harbor",
            "A market correcting itself calmly",
            "A balanced bridge with no stress",
        ],
        "question_ko": "이 장은 미국의 재정 경로를 어떤 이미지로 묘사하는가?",
        "choices_ko": [
            "정상적으로는 멈출 수 없는 열차",
            "안전하게 항구로 돌아오는 배",
            "차분히 스스로 조정되는 시장",
            "아무 스트레스가 없는 균형 잡힌 다리",
        ],
        "answer_index": 0,
        "explanation_en": "The train metaphor is used to describe fiscal and monetary momentum that is now hard to reverse.",
        "explanation_ko": "열차 비유는 되돌리기 어려운 재정·통화 관성을 설명하기 위해 쓰인다.",
    },
    {
        "chapter_id": "12-embrace-deflation",
        "question_en": "What claim about deflation is central to this chapter?",
        "choices_en": [
            "Deflation can be healthy under productivity growth",
            "Deflation is always destructive",
            "Deflation only benefits governments",
            "Deflation eliminates all debt instantly",
        ],
        "question_ko": "이 장의 중심 주장은 디플레이션에 대해 무엇인가?",
        "choices_ko": [
            "생산성 상승 아래에서는 디플레이션이 건강할 수 있다",
            "디플레이션은 언제나 파괴적이다",
            "디플레이션은 정부에만 이익이 된다",
            "디플레이션은 즉시 모든 부채를 없앤다",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter defends productivity-driven deflation as a sign of abundance rather than disease.",
        "explanation_ko": "이 장은 생산성에 기반한 디플레이션을 병이 아니라 풍요의 신호로 옹호한다.",
    },
    {
        "chapter_id": "13-bitcoin-fixes-this",
        "question_en": "How is Bitcoin mainly described in this chapter?",
        "choices_en": [
            "As state-free money and a monetary breakthrough",
            "As a temporary meme asset",
            "As a replacement for electricity",
            "As a central-bank instrument",
        ],
        "question_ko": "이 장에서 비트코인은 주로 어떻게 묘사되는가?",
        "choices_ko": [
            "국가 바깥의 화폐이자 통화적 돌파구",
            "일시적 밈 자산",
            "전기를 대체하는 기술",
            "중앙은행 도구",
        ],
        "answer_index": 0,
        "explanation_en": "Bitcoin is presented as a state-free monetary network that directly answers fiat defects.",
        "explanation_ko": "비트코인은 법정화폐의 결함에 답하는 국가 바깥의 통화 네트워크로 제시된다.",
    },
    {
        "chapter_id": "14-skepticism",
        "question_en": "According to this chapter, what causes much skepticism toward Bitcoin?",
        "choices_en": [
            "Confusing Bitcoin with the wider crypto world",
            "Too much historical familiarity",
            "An absence of media coverage",
            "Its status as a central-bank product",
        ],
        "question_ko": "이 장에 따르면 비트코인 회의론의 큰 원인 중 하나는 무엇인가?",
        "choices_ko": [
            "비트코인을 더 넓은 크립토 세계와 혼동하는 것",
            "역사적 친숙성이 너무 큰 것",
            "미디어 보도가 전혀 없는 것",
            "중앙은행 상품이라는 점",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter says skepticism often comes from category confusion rather than from Bitcoin itself.",
        "explanation_ko": "이 장은 회의론의 상당수가 비트코인 자체보다 범주 혼동에서 나온다고 본다.",
    },
    {
        "chapter_id": "15-why-we-will-be-saved-decentralization",
        "question_en": "What broader trend is presented as grounds for optimism?",
        "choices_en": [
            "Technological decentralization",
            "Permanent monetary centralization",
            "The end of all market competition",
            "A return to barter villages",
        ],
        "question_ko": "이 장이 낙관의 근거로 제시하는 더 큰 흐름은 무엇인가?",
        "choices_ko": [
            "기술적 탈중앙화",
            "영구적 통화 중앙집중",
            "모든 시장 경쟁의 종식",
            "물물교환 마을로의 회귀",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter ties optimism to a wider trend toward decentralization in technology and society.",
        "explanation_ko": "이 장은 낙관의 근거를 기술과 사회 전반의 탈중앙화 흐름에 둔다.",
    },
    {
        "chapter_id": "16-how-this-unfolds",
        "question_en": "What is volatility treated as in this chapter?",
        "choices_en": [
            "A normal part of transition",
            "Proof that the thesis has failed",
            "Evidence that debt is harmless",
            "A sign that fiat is stable",
        ],
        "question_ko": "이 장에서 변동성은 무엇으로 다뤄지는가?",
        "choices_ko": [
            "전환 과정의 정상적 일부",
            "논지가 실패했다는 증거",
            "부채가 무해하다는 증거",
            "법정화폐가 안정적이라는 신호",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter says volatility belongs to real-time transition rather than serving as a refutation of the thesis.",
        "explanation_ko": "이 장은 변동성을 논지의 반증이 아니라 실제 전환의 일부로 본다.",
    },
    {
        "chapter_id": "17-roadmap-for-the-next-decade",
        "question_en": "What is expected to force major change over the next decade?",
        "choices_en": [
            "Escalating crisis leading toward monetary reset",
            "A smooth and effortless reform process",
            "The disappearance of asset bubbles",
            "A permanent halt to fiscal stress",
        ],
        "question_ko": "향후 10년 동안 큰 변화를 강제할 것으로 예상되는 것은 무엇인가?",
        "choices_ko": [
            "통화 리셋으로 이어지는 점증적 위기",
            "매끄럽고 손쉬운 개혁 과정",
            "자산 버블의 소멸",
            "재정 압박의 영구 중단",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter expects crisis, not smooth reform, to force a monetary reset.",
        "explanation_ko": "이 장은 매끈한 개혁이 아니라 위기가 통화 리셋을 강제할 것으로 본다.",
    },
    {
        "chapter_id": "18-greshams-law-inflation-hyperinflation",
        "question_en": "What does Gresham’s Law describe here?",
        "choices_en": [
            "Bad money being spent while good money is hoarded",
            "Gold replacing all prices immediately",
            "Governments refusing to print money",
            "Banks eliminating confidence risk",
        ],
        "question_ko": "이 장에서 그레셤의 법칙은 무엇을 설명하는가?",
        "choices_ko": [
            "나쁜 돈은 쓰고 좋은 돈은 쌓아두는 현상",
            "금이 즉시 모든 가격을 대체하는 것",
            "정부가 돈 찍기를 거부하는 것",
            "은행이 신뢰 리스크를 제거하는 것",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter uses Gresham’s Law to show how people behave when monetary confidence starts to fracture.",
        "explanation_ko": "이 장은 그레셤의 법칙으로 통화 신뢰가 흔들릴 때 사람들이 어떻게 행동하는지 설명한다.",
    },
    {
        "chapter_id": "19-investment-implications-traditional-assets",
        "question_en": "What distinction becomes crucial when evaluating traditional assets?",
        "choices_en": [
            "Nominal returns versus real purchasing power",
            "Morning trades versus afternoon trades",
            "Domestic assets versus foreign language assets",
            "Weekday prices versus weekend prices",
        ],
        "question_ko": "전통 자산을 평가할 때 결정적으로 중요해지는 구분은 무엇인가?",
        "choices_ko": [
            "명목 수익과 실질 구매력",
            "오전 거래와 오후 거래",
            "국내 자산과 외국어 자산",
            "평일 가격과 주말 가격",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter stresses that fiat disorder can inflate nominal gains while real purchasing power erodes.",
        "explanation_ko": "이 장은 법정화폐 혼란 아래에서는 명목 수익이 커 보여도 실질 구매력은 악화될 수 있다고 본다.",
    },
    {
        "chapter_id": "20-investment-implications-bitcoin",
        "question_en": "Why is Bitcoin described as an asymmetric investment opportunity?",
        "choices_en": [
            "Because its upside is tied to monetary repricing",
            "Because it has no downside at all",
            "Because governments guarantee its price",
            "Because it avoids all volatility",
        ],
        "question_ko": "비트코인이 비대칭적 투자 기회로 불리는 이유는 무엇인가?",
        "choices_ko": [
            "상승 여지가 통화적 재가격 책정과 연결되기 때문",
            "하락 가능성이 전혀 없기 때문",
            "정부가 가격을 보장하기 때문",
            "변동성이 전혀 없기 때문",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter links Bitcoin’s upside to a possible revaluation of money itself, not just ordinary adoption growth.",
        "explanation_ko": "이 장은 비트코인의 상승 여지를 단순 채택 증가가 아니라 화폐 자체의 재가격 책정과 연결한다.",
    },
    {
        "chapter_id": "21-policy-responses",
        "question_en": "What policy fork does the chapter present?",
        "choices_en": [
            "Restoring limits versus deepening fiat management",
            "Ending all trade versus ending all industry",
            "Replacing money with barter versus replacing markets with commands",
            "Lowering population versus lowering productivity",
        ],
        "question_ko": "이 장이 제시하는 정책적 갈림길은 무엇인가?",
        "choices_ko": [
            "한계 복원과 더 깊은 법정화폐 관리 사이의 선택",
            "모든 무역 종식과 모든 산업 종식 사이의 선택",
            "화폐를 물물교환으로 대체할지 명령으로 시장을 대체할지의 선택",
            "인구 감소와 생산성 감소 사이의 선택",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter contrasts institutional restraint with continued interventionist fiat management.",
        "explanation_ko": "이 장은 제도적 절제 복원과 개입주의적 법정화폐 관리 지속을 대비한다.",
    },
    {
        "chapter_id": "22-call-to-action",
        "question_en": "What is the first level of preparation emphasized in this chapter?",
        "choices_en": [
            "Personal preparation and understanding",
            "Immediate global treaty reform",
            "Eliminating all market volatility",
            "Waiting for central banks to act",
        ],
        "question_ko": "이 장이 먼저 강조하는 준비의 수준은 무엇인가?",
        "choices_ko": [
            "개인적 준비와 이해",
            "즉각적인 글로벌 조약 개혁",
            "모든 시장 변동성 제거",
            "중앙은행의 대응을 기다리는 것",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter says preparation starts personally: protect yourself, understand the system, and then help others.",
        "explanation_ko": "이 장은 준비가 개인 차원에서 시작된다고 본다. 먼저 자신을 지키고 체제를 이해한 뒤 다른 사람을 도와야 한다.",
    },
    {
        "chapter_id": "23-objections-and-rebuttal",
        "question_en": "What is one main purpose of this chapter’s rebuttals?",
        "choices_en": [
            "To distinguish sound-money discipline from fiat-generated crises",
            "To deny that history matters",
            "To avoid discussing criticism altogether",
            "To argue that every objection is irrational",
        ],
        "question_ko": "이 장의 반박들이 가진 주요 목적 중 하나는 무엇인가?",
        "choices_ko": [
            "건전 화폐의 절제와 법정화폐가 만든 위기를 구분하는 것",
            "역사가 중요하지 않다고 부정하는 것",
            "비판 자체를 피하는 것",
            "모든 반론이 비이성적이라고 주장하는 것",
        ],
        "answer_index": 0,
        "explanation_en": "The chapter repeatedly argues that critics confuse monetary discipline with crises created by debt and fiat distortion.",
        "explanation_ko": "이 장은 비판자들이 건전 화폐의 절제와 부채·법정화폐 왜곡이 만든 위기를 혼동한다고 본다.",
    },
    {
        "chapter_id": "24-conclusion",
        "question_en": "How is inflation characterized in the conclusion?",
        "choices_en": [
            "As a form of theft with personal and social consequences",
            "As a harmless technical detail",
            "As an inevitable sign of progress",
            "As a purely foreign-policy issue",
        ],
        "question_ko": "결론에서 인플레이션은 어떻게 규정되는가?",
        "choices_ko": [
            "개인적·사회적 결과를 낳는 절도의 한 형태",
            "무해한 기술적 세부사항",
            "진보의 불가피한 징표",
            "순전히 외교 정책 문제",
        ],
        "answer_index": 0,
        "explanation_en": "The conclusion frames inflation as monetary theft that damages ordinary life and social trust.",
        "explanation_ko": "결론은 인플레이션을 일상과 사회적 신뢰를 훼손하는 화폐적 절도로 본다.",
    },
]

OUT_DIR = Path("books/the-big-print/quiz/chapters")
OUT_DIR.mkdir(parents=True, exist_ok=True)

schema = {
    "type": "object",
    "required": [
        "chapter_id",
        "question_en",
        "choices_en",
        "question_ko",
        "choices_ko",
        "answer_index",
        "explanation_en",
        "explanation_ko",
    ],
    "notes": {
        "one_question_per_file": True,
        "choices_length": 4,
        "answer_index_zero_based": True,
    },
}

Path("books/the-big-print/quiz/schema.json").write_text(
    json.dumps(schema, ensure_ascii=False, indent=2) + "\n"
)

for quiz in QUIZZES:
    out = OUT_DIR / f"{quiz['chapter_id']}.quiz.json"
    out.write_text(json.dumps(quiz, ensure_ascii=False, indent=2) + "\n")

print(f"Wrote schema and {len(QUIZZES)} quiz files")
